title: Melissa Kendall
name: Author Melissa Kendall 
description: Author & Technical Writer
url: https://melissakendall.ca/
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: Melissa Kendall
  tagline: Author & Technical Writer
  profile_img: images/Avatar.jpg
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; All rights reserved.'
  links:
    - text: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
